// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
//

### Neues Buch anlegen
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createBuch(
    titel: "Test",
    rating: 1,
    art: "KINDLE",
    verlag: "FOO_VERLAG",
    preis: 11.1,
    rabatt: 0.011,
    lieferbar: true,
    datum: "2021-01-31",
    isbn: "3-89722-583-2",
    homepage: "http://acme.com",
    schlagwoerter: ["JAVASCRIPT"]
  )
}

### Vorhandenes Buch aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateBuch(
    _id: "00000000-0000-0000-0000-000000000003",
    titel: "Geaendert",
    rating: 5,
    art: "DRUCKAUSGABE",
    verlag: "FOO_VERLAG",
    preis: 99.99,
    rabatt: 0.099,
    lieferbar: false,
    datum: "2021-01-02",
    isbn: "3-8273-1552-2",
    homepage: "https://acme.com",
    schlagwoerter: [
      "JAVASCRIPT",
      "TYPESCRIPT"
    ],
    version: 1
  )
}

### Vorhandenes Buch loeschen
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteBuch(id: "00000000-0000-0000-0000-000000000004")
}
