' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
@startuml Anwendungskern

!pragma useNewPackage
skinparam classAttributeIconSize 0
skinparam componentStyle uml2

interface Promise<T>

package shared {
  class "sendMail()" as sendMail
  hide sendMail circle
}

package auto {
  package entity {
    class AutoModel
    hide AutoModel circle

    class "validateAuto()" as validateAuto
    hide validateAuto circle

    interface AutoData <<entity>>
  }

  package service #DDDDDD {
    AutoService ..> Promise
    AutoService ..> AutoModel
    AutoService ..> AutoData
    AutoService ..> validateAuto
    AutoService ..> sendMail

    class AutoService << control >> {
      + async findById(id: string): Promise<AutoData | undefined>
      + async find(query?: any): Promise<Array<AutoData>>
      + async create(auto: FilmData): Promise<AutoData>
      + async update(auto: FilmData, version: string): Promise<AutoData>
      + async delete(id: string): Promise<boolean>
    }
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
