' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
@startuml Komponenten

skinparam componentStyle uml2

left to right direction

actor RESTClient

node "Funktionen mit Express" {
  boundary Router
  [Handler Functions]
}

node "Klassen / objektorientiert" {
  [AutoHandler]
  [AutoFileHandler]

  [AutoService]
  [AutoFileService]
}

[sendMail()] as sendMail

entity AutoModel

cloud {
    [Mongoose]
}

cloud {
    [MongDB\nNative Driver]
}

cloud {
    [nodemailer]
}

database "acme (MongoDB)" {
    [Collection Film]
    [GridFS]
}

node {
    [Mailserver]
}


RESTClient ~~> [Router]
[Router] ..> [Handler Functions]
[Handler Functions] ..> [AutoHandler]
[Handler Functions] ..> [AutoFileHandler]

[AutoHandler] --> [AutoService]
[AutoFileHandler] --> [AutoFileService]
[AutoService] ..> [AutoModel]
[AutoFileService] ..> [AutoModel]

[AutoModel] ~~> [Mongoose]
[AutiFileService] ~~> [MongDB\nNative Driver]
[sendMail] ~~> [nodemailer]
[Mongoose] ~~> [Collection Film]
[MongDB\nNative Driver] ~~> [GridFS]

[AutoService] --> [sendMail]
[nodemailer] ~~> [Mailserver]

footer (c) Jürgen Zimmermann

@enduml
