' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
@startuml Use Cases

left to right direction
skinparam packageStyle rect
skinparam componentStyle uml2

actor Gast
actor Admin

rectangle auto {
    Gast --> (Auto suchen)
    Gast --> (Datei herunterladen)
    Admin --> (Auto suchen)
    Admin --> (Auto anlegen)
    Admin --> (Auto ändern)
    Admin --> (Auto löschen)
    Admin --> (Datei hochladen)
    Admin --> (Datei herunterladen)
}

footer (c) Jürgen Zimmermann

@enduml
